import { Listing } from './types';

export const DUMMY_LISTINGS: Listing[] = [
  {
    id: 'l1',
    title: 'Modern 2BHK Apartment',
    price: 18000,
    location: 'Adyar',
    district: 'Chennai',
    houseType: 'Apartment',
    bhk: 2,
    amenities: ['Gym', 'Pool', 'Parking', 'WiFi'],
    imageUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&q=80&w=800',
    roomImages: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80&w=800'
    ],
    description: 'Beautiful modern apartment in the heart of Adyar with all amenities included.',
    createdAt: new Date()
  },
  {
    id: 'l2',
    title: 'Luxury 3BHK Penthouse',
    price: 45000,
    location: 'RS Puram',
    district: 'Coimbatore',
    houseType: 'Apartment',
    bhk: 3,
    amenities: ['Rooftop Garden', 'Pool', 'Parking', 'EV Charging'],
    imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800',
    description: 'Exclusive 3BHK penthouse with panoramic views of the city and Western Ghats.',
    createdAt: new Date()
  },
  {
    id: 'l3',
    title: 'Cozy Studio near IT Park',
    price: 10000,
    location: 'OMR',
    district: 'Chennai',
    houseType: 'Studio',
    bhk: 1,
    amenities: ['Parking', 'Security'],
    imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800',
    description: 'Perfect affordable studio for young professionals working in OMR IT corridor.',
    createdAt: new Date()
  },
  {
    id: 'l4',
    title: 'Traditional Independent House',
    price: 25000,
    location: 'Anna Nagar',
    district: 'Madurai',
    houseType: 'Independent House',
    bhk: 3,
    amenities: ['Garden', 'Parking', 'Water Storage'],
    imageUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&q=80&w=800',
    description: 'Spacious independent house with traditional architecture and modern facilities.',
    createdAt: new Date()
  },
  {
    id: 'l5',
    title: 'Furnished 1BHK Flat',
    price: 15000,
    location: 'Thillai Nagar',
    district: 'Tiruchirappalli',
    houseType: 'Apartment',
    bhk: 1,
    amenities: ['WiFi', 'Parking', 'Security'],
    imageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=800',
    description: 'Fully furnished 1BHK apartment in a peaceful residential locality.',
    createdAt: new Date()
  },
  {
    id: 'l6',
    title: 'Hill View 3BHK Villa',
    price: 35000,
    location: 'Coonoor',
    district: 'Nilgiris',
    houseType: 'Villa',
    bhk: 3,
    amenities: ['View', 'Garden', 'Fireplace'],
    imageUrl: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&q=80&w=800',
    description: 'Beautiful villa surrounded by tea estates with a pleasant year-round climate.',
    createdAt: new Date()
  },
  {
    id: 'l7',
    title: '2BHK Gated Community Apartment',
    price: 22000,
    location: 'Alagapuram',
    district: 'Salem',
    houseType: 'Apartment',
    bhk: 2,
    amenities: ['Security', 'Gym', 'Parking'],
    imageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=800',
    description: 'Well-maintained apartment in a prime gated community in Salem.',
    createdAt: new Date()
  },
  {
    id: 'l8',
    title: 'Spacious 2BHK House',
    price: 14000,
    location: 'Kovilpatti',
    district: 'Thoothukudi',
    houseType: 'Independent House',
    bhk: 2,
    amenities: ['Parking', 'Water Storage'],
    imageUrl: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&q=80&w=800',
    description: 'Calm residential area, perfect for a small family.',
    createdAt: new Date()
  },
  {
    id: 'l9',
    title: 'Beach Town 2BHK Flat',
    price: 16000,
    location: 'Nagercoil',
    district: 'Kanyakumari',
    houseType: 'Apartment',
    bhk: 2,
    amenities: ['Balcony', 'Parking'],
    imageUrl: 'https://images.unsplash.com/photo-1502672023488-70e25813eb80?auto=format&fit=crop&q=80&w=800',
    description: 'Breezy apartment close to the city center and scenic spots.',
    createdAt: new Date()
  },
  {
    id: 'l10',
    title: 'Premium 4BHK Villa',
    price: 60000,
    location: 'Avinashi Road',
    district: 'Tiruppur',
    houseType: 'Villa',
    bhk: 4,
    amenities: ['Private Pool', 'Gym', 'Security', 'Garden'],
    imageUrl: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&q=80&w=800',
    description: 'Lavish villa with modern aesthetic interiors.',
    createdAt: new Date()
  },
  {
    id: 'l11',
    title: 'Comfortable 2BHK',
    price: 12000,
    location: 'Palayamkottai',
    district: 'Tirunelveli',
    houseType: 'Apartment',
    bhk: 2,
    amenities: ['Parking', 'WiFi'],
    imageUrl: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80&w=800',
    description: 'Affordable and secure flat in the educational hub of the city.',
    createdAt: new Date()
  },
  {
    id: 'l12',
    title: '1BHK Compact House',
    price: 8000,
    location: 'Katpadi',
    district: 'Vellore',
    houseType: 'Independent House',
    bhk: 1,
    amenities: ['Water Storage'],
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800',
    description: 'Neat and compact house near the university area.',
    createdAt: new Date()
  }
];
